name: Deploy GH Pages - Eleventy

on:
  # trigger when something is pushed to the branch main
  push: 
    branches: [ "main" ]
  # make it possible to trigger manually, useful for debugging
  workflow_dispatch: 

# permissions
permissions:
  contents: read
  pages: write
  id-token: write

# what should be done
jobs:
  # build stage
  build:
    # this is the (docker) image used to run the steps below
    runs-on: ubuntu-latest

    steps:
      # checkout the branch
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies and build
        uses: actions/setup-node@v5
        run: npm ci
        run: npx @11ty/eleventy
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './site'
  
  # deploy stage
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.pages_url }}
    
    steps:
      # deploy the content
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
